# same as black
line-length = 88
indent-width = 4

# assume Python 3.10
target-version = "py310"


[lint]
select = ["ALL"]
ignore = [
    "ANN",  # type annotations
    "PLR",  # pylint refactor
    "N812",  # lowercase imports
    ]


[lint.pydocstyle]
convention = "numpy"

[format]
# like black, use double quotes for strings.
quote-style = "double"

# like black, indent with spaces, rather than tabs.
indent-style = "space"

# like black, respect magic trailing commas.
skip-magic-trailing-comma = false

# like black, automatically detect the appropriate line ending.
line-ending = "auto"